name: Generate Daily Blog Post

on:
  schedule:
    # Runs every day at midnight UTC. You can change this.
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  generate-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Run post generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python daily_post_generator.py

      - name: Commit and push new post
        run: |
          git config --global user.name 'Automated Blogger'
          git config --global user.email 'actions@github.com'
          git add content/blog/*.md
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "feat: add new daily blog post"
            git push
          else
            echo "No new post generated, nothing to commit."
          fi
